Completed css-brochure-form exercise. -Janice Lee
janiicelee/c0122-code-solutions pull request #15
Opened 2022-01-27 04:43 UTC by janiicelee

<img width="493" alt="Screen Shot 2022-01-26 at 8 42 08 PM" src="https://user-images.githubusercontent.com/57986882/151293369-c9468c20-319d-406d-9331-9eea5fd02e13.png">

2022-01-27 18:14 UTC, codingcodymiller requested changes
Hey Janice! The color of your header and submit button do not match the example, please revise and submit a new screenshot with your revision.

2022-01-27 18:49 UTC, janiicelee commented
![Screen Shot 2022-01-27 at 10 48 16 AM](https://user-images.githubusercontent.com/57986882/151424233-c952ff5f-8806-45b8-8145-26a666cd4b7b.png)

2022-01-28 19:10 UTC, codingcodymiller requested changes
Hey Janice! Your `select` element seems to be slightly misaligned with the other `input` elements, and there is too much space between the `select` element and the submit `button`, please revise and submit a new screenshot with your revision.

2022-01-28 19:33 UTC, janiicelee commented
![Screen Shot 2022-01-28 at 11 31 54 AM](https://user-images.githubusercontent.com/57986882/151609969-9db03122-e096-4f19-8e8e-6ed08462a38d.png)

I think I tried my best on the submit button, but not sure if its accurate.. haha.

2022-01-28 23:14 UTC, codingcodymiller requested changes

2022-01-28 23:14 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  font-family: "Brandon Grotesque", sans-serif !important;
🤢 

Why `!important`? You can remove that.

2022-01-28 23:22 UTC, janiicelee commented on css-brochure-form/styles.css
> +  font-family: "Brandon Grotesque", sans-serif !important;
I get this `font-family-no-missing-generic-family-keyword` error and I found the solution on google to fix that stylelint error..!

2022-01-31 17:28 UTC, codingcodymiller approved these changes

2022-02-05 06:11 UTC, merged