Css two column layout. -Janice Lee
janiicelee/c0122-code-solutions pull request #20
Opened 2022-01-29 01:41 UTC by janiicelee

![Screen Shot 2022-01-28 at 5 39 28 PM](https://user-images.githubusercontent.com/57986882/151642399-76d5cad5-dcce-4a9a-8815-86a49f5add82.png)

2022-01-31 18:26 UTC, codingcodymiller requested changes

2022-01-31 18:26 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +      <div class="column">
How big is the column? Your `column` class tells me nothing about its purpose.

2022-01-31 18:26 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +      <div class="header">
Isn't this a `column` of some sort? You should use a `column` class to properly set up your layout class structure.

2022-01-31 18:26 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  display: flex;
If you find yourself trying to apply `display: flex` to a `column` class element, that really means you need a `row` class element **_inside_** that `column` class element. Your two divs in that `column` (one for the image and one for the text) should be their own `column` class elements inside that `row` within this column.

2022-01-31 21:05 UTC, janiicelee commented
![Screen Shot 2022-01-31 at 1 04 03 PM](https://user-images.githubusercontent.com/57986882/151872971-c31e34ca-61f6-4612-8707-5114b0fcd542.png)

2022-01-31 22:55 UTC, codingcodymiller requested changes

2022-01-31 22:55 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  float: left;
Try doing this without using `float`

2022-02-01 00:57 UTC, janiicelee commented
![Screen Shot 2022-01-31 at 4 57 51 PM](https://user-images.githubusercontent.com/57986882/151897382-af9c3cee-8d93-4022-b901-385f36f59336.png)

2022-02-01 23:27 UTC, codingcodymiller approved these changes

2022-02-05 06:12 UTC, merged