Completed css-canvas-medical exercise -Janice Lee
janiicelee/c0122-code-solutions pull request #26
Opened 2022-02-01 21:06 UTC by janiicelee

![Screen Shot 2022-02-01 at 1 03 52 PM](https://user-images.githubusercontent.com/57986882/152051416-35403139-a972-4c70-8d51-e762ce6d378a.png)
![Screen Shot 2022-02-01 at 1 04 23 PM](https://user-images.githubusercontent.com/57986882/152051430-90601cb9-c4d7-4bcf-b5e6-e507faabeac0.png)
![Screen Shot 2022-02-01 at 1 04 44 PM](https://user-images.githubusercontent.com/57986882/152051433-e732974f-9950-46e1-b163-650bfe5fdf04.png)

2022-02-02 01:27 UTC, codingcodymiller requested changes
Hey Janice! This page seems too wide as compared to the example, it's especially apparent in the hero image section. Additionally, the button in the navbar is not properly aligned with the links it is next to. Please revise and submit a new screenshot with your revision.

2022-02-04 01:10 UTC, janiicelee commented
![127 0 0 1_5500_css-canvas-medical_index html (1)](https://user-images.githubusercontent.com/57986882/152455797-cdae78de-6a94-4f7a-9235-75669d38ee2c.png)

2022-02-04 18:44 UTC, codingcodymiller requested changes

2022-02-04 18:44 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column-one-third"></div>
Empty `column` elements are a no-no. Instead you can control where the `column` elements place themselves in the `row` by adding an additional class with `justify-content` applied to it to position the flexbox's children where you want them. In this case, you would likely use the `space-between` value 🤓

2022-02-04 18:44 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column-fourth"></div>
Same here, no empty columns. For this, you can just make the `column-fourth` before this into a `column-half` to take up that extra space.

2022-02-05 19:12 UTC, janiicelee commented
![127 0 0 1_5500_css-canvas-medical_index html](https://user-images.githubusercontent.com/57986882/152655541-8eccc5c4-2551-45eb-b11f-9e5042e07604.png)

2022-02-07 18:44 UTC, codingcodymiller requested changes

2022-02-07 18:44 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column-two">
`column-two`? This should be named after its measurement.

2022-02-07 18:44 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +}
Remember, the only styling on `column` classes should be either `flex-basis` or `width`. If you need additional styling on a `column` element, you need to make an additional class that you can add **_in addition_** to the `column` class

2022-02-09 04:56 UTC, thebearingedge requested changes
Ok, it's looking good, but we don't want to have a column-half and a column-one-half. or a style-half and a style-one-half. Try applying your colors to sections.

```css
.locations {
  color: your grey color;
  background-color: your other grey color;
}
```

2022-02-09 07:52 UTC, janiicelee commented
@thebearingedge Hi Tim! So do you mean I have to rename the css ruleset that contains the styles for the columns..? or do I have to remove all of them and make a new class? Regarding locations, I thought it was reasonable to indicate the columns for the location.. Can you give me more advice on this part? Thank you!

2022-02-09 16:37 UTC, thebearingedge commented
Hi Janice, please message me on slack

2022-02-10 01:28 UTC, janiicelee commented
![127 0 0 1_5500_css-canvas-medical_index html (1)](https://user-images.githubusercontent.com/57986882/153319546-fb52ca07-4e9d-43d1-a62e-f4f2ec60e2aa.png)

2022-02-10 15:59 UTC, thebearingedge approved these changes

2022-02-10 18:01 UTC, merged